version: "3.7"

services:
  node-mysql-timeline:
    image: xinjn/timeline-node-mysql # 指定镜像
    restart: always # 自动重启
    ports: # 端口映射
      - 4444:8000
    networks: # 网络通信
      - app-timeline

  react-nginx-node-timeline:
    image: xinjn/timeline-react-nginx-node # 指定镜像
    restart: always # 自动重启
    depends_on:
      - node-mysql-timeline
    ports: # 端口映射
      - 9999:80
    networks: # 网络通信
      - app-timeline

networks:
  app-timeline: # 加入网络，引用顶级networks下条目
    driver: bridge
